#!/usr/bin/env python3
"""
Run minimization examples with hierarchical engine (TPU if available).
Outputs: *_minimized_hierarchical.pdb. Compares to *_minimized_cartesian.pdb from the flat pipeline.
"""

from __future__ import annotations

import os
import sys
import time

# Ensure package on path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))

def _check_jax_tpu():
    try:
        import jax
        devices = jax.devices()
        tpu = [d for d in devices if d.platform == "tpu"]
        return len(tpu) > 0, devices, tpu
    except Exception as e:
        return False, [], []


def _atom_count_and_n_res(pdb_path: str) -> tuple[int, int]:
    """Return (n_atoms, n_residues) from PDB MODEL 1."""
    n_atoms = 0
    res_ids = set()
    with open(pdb_path) as f:
        for line in f:
            if line.startswith("ATOM "):
                n_atoms += 1
                try:
                    res_ids.add(int(line[22:26]))
                except ValueError:
                    pass
            if line.startswith("ENDMDL"):
                break
    return n_atoms, len(res_ids)


def run_t1131_tpu(examples_dir: str, device: str) -> bool:
    from horizon_physics.proteins import minimize_full_chain_hierarchical, full_chain_to_pdb
    from horizon_physics.proteins.hierarchical import hierarchical_result_for_pdb

    SEQUENCE = (
        "FVPEEQYNKDFNFLYDYAVIHNLVMDGFSEEDGQYNWDFAKNPDSSRSDESIAYVKELQKLKREDAINFGANAWVLNHNIGFDYKTLKNHQFNLTDANENHSFVVEYWNLKNDETGRHTFWDSVIGEKYGEYLYNADEDTRINGKLKTPYAWVKQILYGIEDAGAPGFSSISA"
    )
    assert len(SEQUENCE) == 173

    print("=== T1131 Hormaphis cornu (TPU/hierarchical) ===")
    start = time.time()
    pos, z_list = minimize_full_chain_hierarchical(
        SEQUENCE,
        include_sidechains=True,
        device=device,
        grouping_strategy="residue",
        max_iter_stage1=30,
        max_iter_stage2=40,
        max_iter_stage3=80,
    )
    elapsed = time.time() - start
    print(f"  Minimization: {elapsed:.1f} s")

    result = hierarchical_result_for_pdb(pos, z_list, SEQUENCE, include_sidechains=True)
    pdb_string = full_chain_to_pdb(result)
    pdb_string = f"REMARK   Generated by run_examples_tpu.py (T1131, hierarchical, device={device}) at {time.strftime('%Y-%m-%d %H:%M:%S')}\n{pdb_string}"

    out_hier = os.path.join(examples_dir, "T1131_hormaphis_cornu_minimized_hierarchical.pdb")
    with open(out_hier, "w") as f:
        f.write(pdb_string)
    print(f"  Written: {out_hier}")

    known = os.path.join(examples_dir, "T1131_hormaphis_cornu_minimized_cartesian.pdb")
    ok = True
    if os.path.isfile(known):
        n_hier, res_hier = _atom_count_and_n_res(out_hier)
        n_cart, res_cart = _atom_count_and_n_res(known)
        print(f"  Check: hierarchical {n_hier} atoms, {res_hier} residues | cartesian {n_cart} atoms, {res_cart} residues")
        if res_hier != 173 or res_cart != 173:
            print("  WARNING: expected 173 residues")
            ok = False
        if n_hier != n_cart:
            print(f"  WARNING: atom count mismatch (hierarchical {n_hier} vs cartesian {n_cart})")
            ok = False
        else:
            print("  OK: atom count and residue count match cartesian.")
    else:
        print("  (no cartesian PDB to compare; run T1131.py first)")
    return ok


def run_t1037_tpu(examples_dir: str, device: str) -> bool:
    from horizon_physics.proteins import minimize_full_chain_hierarchical, full_chain_to_pdb
    from horizon_physics.proteins.hierarchical import hierarchical_result_for_pdb

    SEQUENCE = (
        "SKINFYTTTIETLETEDQNNTLTTFKVQNVSNASTIFSNGKTYWNFARPSYISNRINTFKNNPGVLRQLLNTSYGQSSLWAKHLLGEEKNVTGDFVLAGNARESASENRLKSLELSIFNSLQEKDKGAEGNDNGSISIVDQLADKLNKVLRGGTKNGTSIYSTVTPGDKSTLHEIKIDHFIPETISSFSNGTMIFNDKIVNAFTDHFVSEVNRMKEAYQELETLPESKRVVHYHTDARGNVMKDGKLAGNAFKSGHILSELSFDQITQDDNEMLKLYNEDGSPINPKGAVSNEQKILIKQTINKVLNQRIKENIRYFKDQGLVIDTVNKDGNKGFHFHGLDKSIMSEYTDDIQLTEFDISHVVSDFTLNSILASIEYTKLFTGDPANYKNMVDFFKRVPATYTN"
    )
    assert len(SEQUENCE) == 404

    print("=== T1037 S0A2C3d4 (TPU/hierarchical) ===")
    start = time.time()
    pos, z_list = minimize_full_chain_hierarchical(
        SEQUENCE,
        include_sidechains=True,
        device=device,
        grouping_strategy="residue",
        max_iter_stage1=25,
        max_iter_stage2=35,
        max_iter_stage3=60,
    )
    elapsed = time.time() - start
    print(f"  Minimization: {elapsed/60:.1f} min")

    result = hierarchical_result_for_pdb(pos, z_list, SEQUENCE, include_sidechains=True)
    pdb_string = full_chain_to_pdb(result)
    pdb_string = f"REMARK   Generated by run_examples_tpu.py (T1037, hierarchical, device={device}) at {time.strftime('%Y-%m-%d %H:%M:%S')}\n{pdb_string}"

    out_hier = os.path.join(examples_dir, "T1037_S0A2C3d4_minimized_hierarchical.pdb")
    with open(out_hier, "w") as f:
        f.write(pdb_string)
    print(f"  Written: {out_hier}")

    known = os.path.join(examples_dir, "T1037_S0A2C3d4_minimized_cartesian.pdb")
    ok = True
    if os.path.isfile(known):
        n_hier, res_hier = _atom_count_and_n_res(out_hier)
        n_cart, res_cart = _atom_count_and_n_res(known)
        print(f"  Check: hierarchical {n_hier} atoms, {res_hier} residues | cartesian {n_cart} atoms, {res_cart} residues")
        if res_hier != 404 or res_cart != 404:
            print("  WARNING: expected 404 residues")
            ok = False
        if n_hier != n_cart:
            print(f"  WARNING: atom count mismatch (hierarchical {n_hier} vs cartesian {n_cart})")
            ok = False
        else:
            print("  OK: atom count and residue count match cartesian.")
    else:
        print("  (no cartesian PDB to compare; run T1037.py first)")
    return ok


def main():
    examples_dir = os.path.dirname(os.path.abspath(__file__))
    has_tpu, all_devices, tpu_devices = _check_jax_tpu()
    device = "tpu" if has_tpu else "cpu"
    print(f"JAX devices: {all_devices}")
    print(f"Using device: {device}")
    if not has_tpu:
        print("(TPU not available; running on CPU with hierarchical engine)")

    ok1 = run_t1131_tpu(examples_dir, device)
    ok2 = run_t1037_tpu(examples_dir, device)

    print("")
    print("=== Summary ===")
    print(f"  T1131: {'PASS' if ok1 else 'FAIL/CHECK'}")
    print(f"  T1037: {'PASS' if ok2 else 'FAIL/CHECK'}")
    sys.exit(0 if (ok1 and ok2) else 1)


if __name__ == "__main__":
    main()
