#!/usr/bin/env python3
"""
T1037 S0A2C3d4, CASP14 target (404 aa, PDB 6vr4 domain).
Example: full-chain minimization and PDB export (with crambin, insulin_b, T1131).
"""

from horizon_physics.proteins import minimize_full_chain, full_chain_to_pdb
import time
import os

# Exact sequence from CASP14 target T1037 (S0A2C3d4)
SEQUENCE = (
    "SKINFYTTTIETLETEDQNNTLTTFKVQNVSNASTIFSNGKTYWNFARPSYISNRINTFKNNPGVLRQLLNTSYGQSSLWAKHLLGEEKNVTGDFVLAGNARESASENRLKSLELSIFNSLQEKDKGAEGNDNGSISIVDQLADKLNKVLRGGTKNGTSIYSTVTPGDKSTLHEIKIDHFIPETISSFSNGTMIFNDKIVNAFTDHFVSEVNRMKEAYQELETLPESKRVVHYHTDARGNVMKDGKLAGNAFKSGHILSELSFDQITQDDNEMLKLYNEDGSPINPKGAVSNEQKILIKQTINKVLNQRIKENIRYFKDQGLVIDTVNKDGNKGFHFHGLDKSIMSEYTDDIQLTEFDISHVVSDFTLNSILASIEYTKLFTGDPANYKNMVDFFKRVPATYTN"
)

assert len(SEQUENCE) == 404, f"Sequence length error: {len(SEQUENCE)}"

print("=== T1037 S0A2C3d4 Protein Folding ===")
print(f"Sequence length: {len(SEQUENCE)} residues")
print(f"Starting at: {time.strftime('%Y-%m-%d %H:%M:%S')}")

start_time = time.time()

# Full pipeline (Cα-only → full backbone → side-chain packing)
# For 404 aa, fast path is used (n_res > 50); set include_sidechains=False for a quicker first pass
result = minimize_full_chain(
    SEQUENCE,
    include_sidechains=True,
)

elapsed = time.time() - start_time
print(f"Minimization completed in {elapsed/60:.1f} minutes")

pdb_string = full_chain_to_pdb(result)
# Prepend REMARK so the file is visibly from this run
timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
pdb_string = f"REMARK   Generated by T1037.py at {timestamp}\n{pdb_string}"

examples_dir = os.path.dirname(os.path.abspath(__file__))
output_file = os.path.join(examples_dir, "T1037_S0A2C3d4_minimized_cartesian.pdb")
with open(output_file, "w") as f:
    f.write(pdb_string)

print(f"Saved PDB: {output_file}")
print("Done! Open in PyMOL/VMD/ChimeraX to visualize.")