#!/usr/bin/env python3
"""
T1131 g2703, Hormaphis cornu, 173 residues.
Example: full-chain minimization and PDB export (with crambin and insulin_b).
"""

from horizon_physics.proteins import minimize_full_chain, full_chain_to_pdb
import time
import os

# T1131 g2703, Hormaphis cornu, 173 residues
SEQUENCE = (
    "FVPEEQYNKDFNFLYDYAVIHNLVMDGFSEEDGQYNWDFAKNPDSSRSDESIAYVKELQKLKREDAINFGANAWVLNHNIGFDYKTLKNHQFNLTDANENHSFVVEYWNLKNDETGRHTFWDSVIGEKYGEYLYNADEDTRINGKLKTPYAWVKQILYGIEDAGAPGFSSISA"
)

assert len(SEQUENCE) == 173, f"Sequence length error: {len(SEQUENCE)}"

print("=== T1131 Hormaphis cornu Protein Folding ===")
print(f"Sequence length: {len(SEQUENCE)} residues")
print(f"Starting at: {time.strftime('%Y-%m-%d %H:%M:%S')}")

start_time = time.time()

result = minimize_full_chain(
    SEQUENCE,
    include_sidechains=True,
)

elapsed = time.time() - start_time
print(f"Minimization completed in {elapsed:.1f} s")

pdb_string = full_chain_to_pdb(result)
timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
pdb_string = f"REMARK   Generated by T1131.py at {timestamp}\n{pdb_string}"

examples_dir = os.path.dirname(os.path.abspath(__file__))
output_file = os.path.join(examples_dir, "T1131_hormaphis_cornu_minimized_cartesian.pdb")
with open(output_file, "w") as f:
    f.write(pdb_string)

print(f"Saved PDB: {output_file}")
print("Done! Open in PyMOL/VMD/ChimeraX to visualize.")
